import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav3 from "@/components/Nav3";
import Nav2 from "@/components/Nav2";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <header>
            <Nav3 />
            
          </header>
            <main>
              {children}
            </main>
          <footer>
            <Footer />
          </footer>
      </body>
    </html>
  );
}
